apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-receiver
  namespace: argocd
data:
  webhook.sh: |
    #!/bin/bash
    # Simple webhook receiver that triggers ArgoCD sync
    
    while true; do
      # Listen for webhook (simplified example)
      echo "Webhook received - triggering ArgoCD sync..."
      
      # Trigger ArgoCD application sync
      argocd app sync cicd-demo --server argocd-server.argocd.svc.cluster.local:443 --insecure
      
      sleep 10
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-receiver
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-receiver
  template:
    metadata:
      labels:
        app: webhook-receiver
    spec:
      containers:
      - name: webhook
        image: alpine:latest
        command: ["/bin/sh"]
        args: ["/scripts/webhook.sh"]
        volumeMounts:
        - name: script
          mountPath: /scripts
      volumes:
      - name: script
        configMap:
          name: webhook-receiver
          defaultMode: 0755
