apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
  labels:
    app: cicd-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      containers:
      - name: cicd-demo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: ENVIRONMENT
          value: "{{ .Values.env.ENVIRONMENT }}"
        - name: APP_VERSION
          value: "{{ .Values.env.APP_VERSION }}"
