apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      containers:
      - name: cicd-demo
        image: ${IMAGE_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
        ports:
        - containerPort: 5000
        env:
        - name: ENVIRONMENT
          value: production
        - name: APP_VERSION
          value: ${IMAGE_TAG}
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-demo
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: cicd-demo
  type: ClusterIP
