name: CI/CD with Registry-based GitOps

on:
  workflow_dispatch:
    inputs:
      approach:
        description: 'Deployment approach'
        required: true
        default: 'registry-based'
        type: choice
        options:
        - registry-based

# Registry-triggered GitOps: ArgoCD Image Updater monitors GHCR
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: Run tests
        run: pytest

  build-and-publish:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=registry-latest
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Registry-based deployment notification
        run: |
          echo "🚀 Image pushed to GHCR (Registry-based GitOps)!"
          echo "📦 Images:"
          echo "${{ steps.meta.outputs.tags }}" | sed 's/,/\n/g' | sed 's/^/  - /'
          echo ""
          echo "🔄 ArgoCD Image Updater will automatically:"
          echo "  1. Monitor GHCR for new 'registry-latest' tag"
          echo "  2. Update Helm values.yaml automatically"
          echo "  3. Trigger ArgoCD sync and deployment"
          echo ""
          echo "📊 Monitor progress:"
          echo "  kubectl logs -f deployment/argocd-image-updater -n argocd"
