name: CI/CD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'helm/cicd-demo/values.yaml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'helm/cicd-demo/values.yaml'
  workflow_dispatch:

# Simplified CI/CD workflow: test, build, push image
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: Run tests
        run: pytest

  build-and-publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest

  release:
    name: Update Helm chart values
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Update Helm values
        run: |
          sed -i "s|repository: .*|repository: ghcr.io/${{ github.repository }}|" helm/cicd-demo/values.yaml
          sed -i "s|tag: .*|tag: \"${{ github.sha }}\"|" helm/cicd-demo/values.yaml
      - name: Commit and push chart update
        run: |
          git add helm/cicd-demo/values.yaml
          git commit -m "ci: update Helm chart values to ${{ github.sha }} [ci skip]"
          git push
  #   runs-on: ubuntu-latest
    # needs: build
    # if: github.ref == 'refs/heads/master'
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2
    #   - name: Log in to GitHub Container Registry
    #     uses: docker/login-action@v1
    #     with:
    #       registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Deploy to Kubernetes
      #   uses: azure/setup-kubectl@v1
      #   with:
      #     version: 'latest'
      # - name: Apply Kubernetes manifests
      #   run: |
      #     kubectl apply -f deployment.yaml
      #     kubectl apply -f service.yaml
      