name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# Simplified CI/CD workflow: test, build, push image
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: Run tests
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ghcr.io/${{ github.repository }}:latest

  # deploy:
  #   runs-on: ubuntu-latest
    # needs: build
    # if: github.ref == 'refs/heads/master'
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2
    #   - name: Log in to GitHub Container Registry
    #     uses: docker/login-action@v1
    #     with:
    #       registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Deploy to Kubernetes
      #   uses: azure/setup-kubectl@v1
      #   with:
      #     version: 'latest'
      # - name: Apply Kubernetes manifests
      #   run: |
      #     kubectl apply -f deployment.yaml
      #     kubectl apply -f service.yaml
      