name: CI/CD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'helm/cicd-demo/values.yaml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'helm/cicd-demo/values.yaml'
  workflow_dispatch:

# Simplified CI/CD workflow: test, build, push image
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: Run tests
        run: pytest

  build-and-publish:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Update Helm chart for ArgoCD
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write  # Allow writing to repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}  # Use Personal Access Token instead
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Extract image tag from build
        id: image_tag
        run: |
          # Get the image tag that was just built
          echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
      
      - name: Update Helm values
        run: |
          # Update the image repository and tag in values.yaml
          sed -i "s|repository: .*|repository: ghcr.io/${{ github.repository }}|" helm/cicd-demo/values.yaml
          sed -i "s|tag: .*|tag: \"${{ steps.image_tag.outputs.tag }}\"|" helm/cicd-demo/values.yaml
          
          # Show the changes for verification
          echo "📝 Updated values.yaml (Git-based GitOps approach):"
          cat helm/cicd-demo/values.yaml
      
      - name: Commit and push changes
        run: |
          git add helm/cicd-demo/values.yaml
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🚀 deploy: update image to ${{ steps.image_tag.outputs.tag }} [ci skip]"
            git push origin master
            echo "✅ Helm chart updated - ArgoCD will detect and deploy the changes (Git-based GitOps)"
          fi